E8/contact_manager/contact/urls.py
from django.urls import path

from . import views
app_name = 'contact'
urlpatterns = [
    # path('', views.index, name='index'),


        # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:person_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:person_id>/edit/', views.edit, name='edit'),
    # ex: /polls/5/vote/
    path('add/', views.add, name='add'),
 

]

E8/contact_manager/contact_manager/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
]

E8/contact_manager/contact/models.py
from django.db import models

# Create your models here.
 


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name =  models.CharField(max_length=200)
    email =   models.CharField(max_length=200)
    phone_number =  models.CharField(max_length=200)
    notes =  models.CharField(max_length=200) 
    def __str__(self):
        return self.first_name
 

E8/contact_manager/contact/forms.py
from django import forms


# class RenewBookForm(forms.Form):
#     renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    
# class NameForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)


# class UserForm(forms.Form):
#     username = forms.CharField(label="用户名", max_length=128)
#     password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput)



class edit_person_form(forms.Form):
    # class Meta:
    #    model = User
    #    fields = []

    first_name = forms.CharField(label="first_name",max_length=200,required = True)
    last_name =  forms.CharField(label="last_name",max_length=200,required = True)
    email =   forms.CharField(label="email",max_length=200,required = True)
    phone_number =  forms.CharField(label="phone number",max_length=200,required = True)
    notes =  forms.CharField(label="notes",max_length=200,required = True)


class add_person_form(forms.Form): 

    first_name = forms.CharField(label="first_name",max_length=200,required = True)
    last_name =  forms.CharField(label="last_name",max_length=200,required = True)
    email =   forms.CharField(label="  email",max_length=200,required = True)
    phone_number =  forms.CharField(label="phone number",max_length=200,required = True)
    notes =  forms.CharField(label="notes",max_length=200,required = True)

E8/contact_manager/contact/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from .models import Person

from django.template import loader

from .forms import edit_person_form,add_person_form
from django.http import HttpResponseRedirect
from django.urls import reverse

# from . import models
# from . import forms

# from django.http import Http404
# def index(request):
#     return HttpResponse("Hello, world. You're at the contact index.")

# def index(request):
#     latest_person_list = Person.objects.order_by('first_name')[:5]
#     output = ', '.join([p.first_name for p in latest_person_list])
#     return HttpResponse(output)

def index(request):
    # latest_person_list = Person.objects.order_by('first_name')[:5]
    latest_person_list = Person.objects.order_by('first_name')

    # template = loader.get_template('contact/index.html')
    context = {
        'latest_person_list': latest_person_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'contact/index.html', context)


def detail(request, person_id): 
    person = get_object_or_404(Person,pk=person_id) 
    return render(request, 'contact/detail.html',{'person':person})
 
 

def edit(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    edit_form = edit_person_form;
    if request.method != 'POST':
        form = edit_form(initial={'first_name': person.first_name, 'last_name': person.last_name,'email': person.email,'phone_number': person.phone_number,'notes': person.notes,}) 
    else:
        form = edit_form(data=request.POST)
        message = 'Please Check!'
        if form.is_valid():
            person.first_name = form.cleaned_data.get('first_name')
            person.last_name = form.cleaned_data.get('last_name')
            person.email = form.cleaned_data.get('email')
            person.phone_number = form.cleaned_data.get('phone_number')
            person.notes = form.cleaned_data.get('notes')
            person.save();
            return HttpResponseRedirect(reverse('contact:detail', args=(person.id,)))
 
    return render(request, 'contact/edit.html', {'form':form,'person':person})


def add(request):
    # person = get_object_or_404(Person, pk=person_id)
    add_form = add_person_form;
    if request.method != 'POST':
    # it not post,create a form
        form = add_form() 
    else:
    # if it is post, data=request.POST to get the data inside the form
        form = add_form(data=request.POST)
        message = 'Please Check!'
        if form.is_valid():
            # form.save(); 
            Person.objects.create(first_name=form.cleaned_data.get('first_name'), last_name=form.cleaned_data.get('last_name'),email = form.cleaned_data.get('email'), phone_number=form.cleaned_data.get('phone_number'),notes=form.cleaned_data.get('notes'))
            return HttpResponseRedirect(reverse('contact:index'))
 
    return render(request, 'contact/add.html', {'form':form})

  



  

E8/contact_manager/contact/templates/contact/add.html
<form action="{% url 'contact:add' %}" method="post">
    <h1>Add Contact</h1>
    <h3>Note: The following fields are all required! </h3> {% csrf_token %} {{ form.as_ul }}
    <br>
    <input type="submit" value="Create Contact">
</form>

E8/contact_manager/contact/templates/contact/detail.html
<h1>
    Contact List: {{person.first_name}} {{person.last_name}}
</h1>


<p>
    <strong>First Name:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.first_name}}
</p>


<p><strong>Last name:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.last_name}}
</p>

<p><strong>Email:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.email}}</p>

<p><strong>Phone Number:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.phone_number}}</p>

<p><strong>Notes:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.notes}}</p>

<!-- <p><strong>Person ID:</strong>
    <br> &nbsp;&nbsp;&nbsp;&nbsp; {{person.id}}
</p> -->


<a href="{% url 'contact:index' %}"> List of people </a> |
<a href="{% url 'contact:edit' person.id %}"> Edit contact</a>

E8/contact_manager/contact/templates/contact/edit.html
<form action="{% url 'contact:edit' person.id %}" method="post">
    <h1>Edit Contact</h1>
    <h3>Note: The following fields are all required! </h3> {% csrf_token %} {{ form.as_ul }}
    <br>
    <input type="submit" value="Update Contact">
</form>

E8/contact_manager/contact/templates/contact/index.html
<h1>Contact List</h1>
{% if latest_person_list %}
<ul>
    {% for person in latest_person_list %}
    <!-- <li><a href="/contact/{{ person.id }}/">{{ person.first_name }}</a></li> -->
    <li>
        <a href="{% url 'contact:detail' person.id %}"> {{ person.first_name }} {{ person.last_name }} </a></li>

    {% endfor %}
</ul>

{% else %}
<p>No person are available.</p>
{% endif %}


<a href="{% url 'contact:add' %}"> Add new contact</a>